serverFiles:
  ## Alerts configuration
  ## Ref: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
  alerting_rules_data.yml:
    groups:
      - name: Downtime
        rules:

        - alert: KubernetesPodNotHealthy
          expr: sum by (namespace, pod) (kube_pod_status_phase{namespace="airbyte-v2-prd", phase=~"Pending|Unknown|Failed""}) > 0
          for: 5m
          labels:
            severity: 'critical'
            team: 'data'
          annotations:
            summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
            description: "Pod has been in a non-ready state for longer than 15 minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    
        - alert: KubernetesPodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total{namespace="airbyte-v2-prd"}[1m]) > 3
          for: 2m
          labels:
            severity: warning
            team: 'data'
          annotations:
            summary: Kubernetes pod crash looping (instance {{ $labels.instance }})
            description: "Pod {{ $labels.pod }} is crash looping\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  
      - name: Containers
        rules:
        - alert: ContainerCpuUsage
          expr: ((sum(rate(container_cpu_usage_seconds_total{namespace="airbyte-v2-prd", image!="", container!="POD", image!=""}[3m]))  by (pod) * 100)) > 70
          for: 1m
          labels:
            severity: 'critical'
            team: 'data'
          annotations:
            title: 'Container CPU usage (instance {{ $labels.namespace }}) {{ $labels.pod }}'
            description: 'Container CPU usage is above 70%'

        - alert: ContainerMemoryUsage
          expr: sum(rate(container_cpu_usage_seconds_total{namespace="airbyte-v2-prd"}[5m])) by (pod) > 3.0e+09
          for: 1m
          labels:
            severity: 'critical'
            team: 'data'
          annotations:
            title: 'High Memory Usage'
            description: 'High Memory Usage (instance {{ $labels.namespace }}) {{ $labels.pod }}'
            
        - alert: ContainerRestarts
          expr: delta(kube_pod_container_status_restarts_total{namespace="airbyte-v2-prd"}[1h]) >= 1
          for: 10s
          labels:
            severity: 'critical'
            team: 'data'
          annotations:
            summary: 'Containers are restarting'
            description: 'The container {{ $labels.container }} in pod {{ $labels.pod }}
              has restarted at least {{ humanize $value}} times in the last hour on instance
              {{ $labels.instance }}.'