## alertmanager ConfigMap entries
##
alertmanagerFiles:
  alertmanager.yml:
    route:
      group_wait: 1s
      group_interval: 5m
      group_by:
        - '...'
      receiver: stg-receiver
      repeat_interval: 0h
      routes:
        - receiver: stg-receiver
          group_wait: 10s
          continue: true
          active_time_intervals:
            - support_hours

  
    time_intervals:
    - name: support_hours
      time_intervals:
        - weekdays: ['monday:friday']
          times:
            - start_time: 12:00
              end_time: 23:00

    receivers:
      - name: stg-receiver
        slack_configs:
          - channel: '#devops-alerts-stg'
            api_url: 'https://hooks.slack.com/services/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'
            send_resolved: true
            icon_url: https://avatars3.githubusercontent.com/u/3380462
            text: >-
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                *Description:* {{ .Annotations.description }}
                *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
                *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}
